language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJRWXVR2NWJKFN4EA
  secret_access_key:
    secure: d0W4M00BtJ8auQU7uXQ9vBRzsEc+a2mAxfwdtNaFUue85RN2ylvfi0fhydpKvgJHunY/kiiZk8hrJxeDHY7ZL/MvZipNnGIMge+9vI290S7hS6oqsJykag5zlaB6MXkr4KTCs1+mmgLACYajzTHq4brcFNiREmK5j2Fd8WGplyA=
  bucket: kkpbucketsource
  upload-dir: processor
  on:
    repo: kk90/AWSprojectImageProcessor
